//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_2308.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        public int tid { get; set; }
        public string tname { get; set; }
        public string tcity { get; set; }
        public Nullable<int> deptid { get; set; }
        public string domain { get; set; }
    }
}
